import React from "react";
import Head from "next/head";
import Footer from "../../shared/Footer/Footer";
import SiteHeader from "../SiteHeader"
import Header from "../Header/Header";

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Properties</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="node_modules/@glidejs/glide/dist/css/glide.core.min.css"
                ></link>
            </Head>
            <Header />
            <div className="flex">
                <aside className="bg-blue-500 w-80">
                    <p>Aqui filtros</p>
                </aside>
                <main className="w-full">
                    <div className="text-base bg-white dark:bg-neutral-900 text-neutral-900 dark:text-neutral-200">
                        <div className="container mx-auto">{children}</div>
                    </div>
                </main>
            </div>
            <Footer />
        </>
    );
};

export default Layout;
