import React, { FC, Fragment } from "react";
import Head from "next/head";
import Footer from "../../shared/Footer/Footer";
import SiteHeader from "../SiteHeader";
import Header from "../Header/Header";
import "@glidejs/glide/dist/css/glide.core.min.css";
import useUser from "../../lib/useUser";
import { getCookies } from "cookies-next";

interface Layout {
    children: React.ReactNode;
    container?: boolean;
}

const Layout: FC<Layout> = ({ children, container = true }) => {
    return (
        <>
            <Head>
                <title>Properties</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>
                <div className="w-full pt-4 text-base bg-white dark:bg-neutral-900 text-neutral-900 dark:text-neutral-200 ">
                    <div className={`${container ? "container mx-auto" : ""} `}>
                        {children}
                    </div>
                </div>
            </main>
            <Footer />
        </>
    );
};

export default Layout;
