export const INITIAL_STATE_NEW_PROPERTY = {
    reference: "",
    title: "",
    description: "",
    price: 0,
    address: "",
    city: "",
    departament: "",
    building: "",
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    contactCellphone: "",
    antiquityYears: "",
    lastAdminprice: 0,
    neighborhood: "",
    propertyType: "",
    offer: "",
    area: "",
    stratum: "",
    bedrooms: 0,
    numElevators: 0,
    numFloor: 0,
    bathrooms: 0,
    garage: 0,
    parking: 0,
    remodelation: 0,
    latitude: 6.228418741427521,
    longitude: -75.5626006542638,
    saleOff: 0,
    images:[],
};

export const NEW_PROPERTY_MOCK = {
    reference: "PR00020",
    title: "Apartamento - primer piso",
    description:
        "Apartamento para estrenar en el barrio Florencia de medellin, con red de gas y parqueadero",
    price: 285000,
    address: "Carerra 78 #110a",
    building: "EDIFICIO LOS LLANOS",
    contactName: "Manuel Rodriguez",
    contactEmail: "correo@prueba",
    contactPhone: "604 8537458",
    contactCellphone: "3205434345",
    antiquityYears: 2,
    published: 1,
    lastAdminprice: 100000,
    neighborhood: "Laureles",
    propertyType: 2,
    offer: 1,
    area: 38,
    stratum: 3,
    bedrooms: 2,
    numElevators: 0,
    numFloor: 1,
    bathrooms: 1,
    garage: 0,
    parking: 1,
    remodelation: 0,
    latitude: 6.248093959565622,
    longitude: -75.59347774688707,
    departament: 5,
    city: "1",
    saleOff: 100000,
    images: [],
    stateId: 1,
};
